name: GitHub Pages

on:
  push:
    branches:
      - main  # Set a branch name to trigger deployment
    paths-ignore:
      - 'readme.md'
      - '.github/workflows/**'

jobs:
  deploy:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@master
      with:
        node-version: 16
    - name: install dependencies
      run: npm install
    - name: package
      run: npm run package
    - name: deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./.webpack/renderer
